# Autogenerated wrapper script for Chemfiles_jll for aarch64-apple-darwin
export libchemfiles

JLLWrappers.@generate_wrapper_header("Chemfiles")
JLLWrappers.@declare_library_product(libchemfiles, "@rpath/libchemfiles.0.10.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libchemfiles,
        "lib/libchemfiles.0.10.4.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
