# Autogenerated wrapper script for Chemfiles_jll for i686-w64-mingw32-cxx03
export libchemfiles

JLLWrappers.@generate_wrapper_header("Chemfiles")
JLLWrappers.@declare_library_product(libchemfiles, "libchemfiles.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libchemfiles,
        "bin\\libchemfiles.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
